# Generated by Django 4.2.2 on 2023-07-02 00:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_alter_project_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
    ]
